name: xlo_mobx
description: Projeto para estudos.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  parse_server_sdk_flutter: ^4.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_modular: ^5.0.3
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  get_it: ^7.6.0
  brasil_fields: ^1.12.0
  image_picker: ^0.8.7+5
  image_cropper: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  mobx_codegen: ^2.3.0
  modular_test: ^2.0.0
  build_runner: ^2.1.4

flutter:
  uses-material-design: true
